language: rust
sudo: false
rust:
  - nightly
  - beta
  - stable
script:
  - cargo build --verbose
  - cargo test --verbose
  - [ $TRAVIS_RUST_VERSION = nightly ] && cargo test --verbose --features unstable
