[package]

name = "osmpbfreader"
version = "0.0.1"
authors = ["Guillaume Pinot <texitoi@texitoi.eu>"]

[dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf.git"

[dependencies.flate2]
[dependencies.log]
