[package]

name = "osmpbfreader"
version = "0.1.0"
authors = ["Guillaume Pinot <texitoi@texitoi.eu>"]

[dependencies]
flate2 = "0.2.13"
byteorder = "0.5.0"
protobuf = "1.0.18"

[dev-dependencies]
log = "0.3.5"
