[package]

name = "osmpbfreader"
version = "0.3.0"
authors = ["Guillaume Pinot <texitoi@texitoi.eu>"]

[dependencies]
flate2 = "0.2.13"
byteorder = "0.5.1"
protobuf = "1.0.18"
compiletest_rs = { version = "*", optional = true }

[dev-dependencies]
log = "0.3.6"

[features]
unstable = ["compiletest_rs"]
