[package]
name = "osmpbfreader"
version = "0.10.1"
authors = ["Guillaume Pinot <texitoi@texitoi.eu>"]
description = "Read OpenStreetMap PBF files in rust."
documentation = "https://docs.rs/osmpbfreader"
repository = "https://github.com/TeXitoi/osmpbfreader-rs"
keywords = ["openstreetmap", "osm", "pbf"]
categories = ["encoding", "science"]
license = "WTFPL"
readme = "README.md"

[badges]
travis-ci = { repository = "TeXitoi/osmpbfreader-rs" }
appveyor = { repository = "TeXitoi/osmpbfreader-rs" }

[dependencies]
flate2 = "0.2.17"
byteorder = "1.0"
protobuf = "1.1"
flat_map = "0.0.4"
futures = "0.1"
futures-cpupool = "0.1"
num_cpus = "1.2"

[dev-dependencies]
log = "0.3.6"
