[package]

name = "osmpbfreader"
version = "0.5.0"
authors = ["Guillaume Pinot <texitoi@texitoi.eu>"]
description = "Read OpenStreetMap PBF files in rust."
documentation = "http://texitoi.github.io/osmpbfreader-rs/"
homepage = "https://github.com/TeXitoi/osmpbfreader-rs"
repository = "https://github.com/TeXitoi/osmpbfreader-rs"
keywords = ["openstreetmap", "osm", "pbf"]
license = "WTFPL"

[dependencies]
flate2 = "0.2.14"
byteorder = "0.5.3"
protobuf = "1.0.22"
compiletest_rs = { version = "0.2.0", optional = true }

[dev-dependencies]
log = "0.3.6"

[features]
unstable = ["compiletest_rs"]
